// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCycuiiPzKiABTINACbFgKr2auA1kF1bXQ',
    appId: '1:1005209899310:android:7bc02f275fb36622756abf',
    messagingSenderId: '1005209899310',
    projectId: 'silah-75e70',
    storageBucket: 'silah-75e70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6d9ibxEXf4w1laIoWFTacWIaEuOcm_Sw',
    appId: '1:1005209899310:ios:32ee726dc4ec6450756abf',
    messagingSenderId: '1005209899310',
    projectId: 'silah-75e70',
    storageBucket: 'silah-75e70.appspot.com',
    iosClientId: '1005209899310-crf6gj08rmdlsja7f192f6950m00s9ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.silahApp',
  );
}
